# Generated by Django 5.1.7 on 2025-03-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='yosh',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
