# Generated by Django 5.1.7 on 2025-03-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_administrator_yosh'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyurtma',
            name='sana',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
